# Generated by Django 3.1.3 on 2020-11-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djboot', '0002_studentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=3),
        ),
    ]
